title: DenverSec
description: "DenverSec is a #CitySec social gathering for anyone interested in information security with everyone welcome! Usually every third Wednesday in Downtown Denver at 7:00 PM."

url: https://denversec.org
baseurl: ""

markdown: kramdown
highlighter: rouge

# navigation:
#  - title: Home
#    url: /
#  - title: Meetups
#    url: /meetups

social:
#   github: denversec
   twitter: DenverSec
   mastodon: DenverSec
   mastodon_instance: infosec.exchange
#   email: info@denversec.org

ical: /meetups.ics

