title: Denver CitySec
description: The Denver CitySec meetup -- a social gathering for anyone interested in information security, held every third Wednesday in Downtown Denver at 7:00 PM.

url: http://denversec.org
baseurl: ""

markdown: kramdown
highlighter: rouge

# navigation:
#  - title: Home
#    url: /
#  - title: Meetups
#    url: /meetups

social:
#   github: denversec
   twitter: DenverCec
#   email: info@denversec.org
